import type { RawDoctorRecord, SourceAdapter } from "./types";

const checkedAt = "2026-09-20T10:00:00.000Z";

const fixtures: RawDoctorRecord[] = [
  {
    sourceRecordKey: "fixture-ict-001",
    sourceName: "Pilot fixture — Islamabad",
    sourceUrl: "https://example.gov.pk/fixtures/islamabad",
    sourceType: "fixture",
    fullName: "Dr. Zoya Ahmed",
    designation: "Medical Officer",
    specialty: "General Medicine",
    pmdcRegistrationNumber: "FIXTURE-ICT-001",
    pmdcStatus: "valid",
    facilityName: "Pakistan Institute of Medical Sciences",
    facilityType: "Federal government hospital",
    facilityAddress: "Ibn-e-Sina Road, G-8/3, Islamabad",
    officialPhone: "051 9261170",
    city: "Islamabad",
    province: "Islamabad Capital Territory",
    governmentEmploymentVerified: true,
    governmentVerifiedAt: checkedAt,
    pmdcVerifiedAt: checkedAt,
    facilityVerifiedAt: checkedAt,
  },
  {
    sourceRecordKey: "fixture-punjab-001",
    sourceName: "Pilot fixture — Lahore",
    sourceUrl: "https://example.gov.pk/fixtures/lahore",
    sourceType: "fixture",
    fullName: "Dr. Ayesha Malik",
    designation: "Women Medical Officer",
    specialty: "General Medicine",
    pmdcRegistrationNumber: "FIXTURE-PUNJAB-001",
    pmdcStatus: "valid",
    facilityName: "Services Hospital Lahore",
    facilityType: "Punjab government teaching hospital",
    facilityAddress: "Jail Road, Lahore",
    officialPhone: "042 99203402",
    city: "Lahore",
    province: "Punjab",
    governmentEmploymentVerified: true,
    governmentVerifiedAt: checkedAt,
    pmdcVerifiedAt: checkedAt,
    facilityVerifiedAt: checkedAt,
  },
  {
    sourceRecordKey: "fixture-sindh-001",
    sourceName: "Pilot fixture — Karachi",
    sourceUrl: "https://example.gov.pk/fixtures/karachi",
    sourceType: "fixture",
    fullName: "Dr. Hamza Siddiqui",
    designation: "Medical Officer",
    specialty: "Internal Medicine",
    pmdcRegistrationNumber: "FIXTURE-SINDH-001",
    pmdcStatus: "valid",
    facilityName: "Jinnah Postgraduate Medical Centre",
    facilityType: "Federal government hospital",
    facilityAddress: "Rafiqui Shaheed Road, Karachi",
    officialPhone: "021 99201300",
    city: "Karachi",
    province: "Sindh",
    governmentEmploymentVerified: true,
    governmentVerifiedAt: checkedAt,
    pmdcVerifiedAt: checkedAt,
    facilityVerifiedAt: checkedAt,
  },
  {
    sourceRecordKey: "fixture-kp-001",
    sourceName: "Pilot fixture — Peshawar",
    sourceUrl: "https://example.gov.pk/fixtures/peshawar",
    sourceType: "fixture",
    fullName: "Dr. Sanaullah Khan",
    designation: "Medical Officer",
    specialty: "General Medicine",
    pmdcRegistrationNumber: "FIXTURE-KP-001",
    pmdcStatus: "valid",
    facilityName: "Lady Reading Hospital",
    facilityType: "Khyber Pakhtunkhwa government hospital",
    facilityAddress: "Soekarno Road, Peshawar",
    officialPhone: "091 9211430",
    city: "Peshawar",
    province: "Khyber Pakhtunkhwa",
    governmentEmploymentVerified: true,
    governmentVerifiedAt: checkedAt,
    pmdcVerifiedAt: checkedAt,
    facilityVerifiedAt: checkedAt,
  },
  {
    sourceRecordKey: "fixture-rejected-001",
    sourceName: "Pilot fixture — rejected record",
    sourceUrl: "https://example.gov.pk/fixtures/rejected",
    sourceType: "fixture",
    fullName: "Dr. Example Expired",
    designation: "Medical Officer",
    specialty: "General Medicine",
    pmdcRegistrationNumber: "FIXTURE-EXPIRED-001",
    pmdcStatus: "expired",
    facilityName: "Example Government Hospital",
    facilityType: "Government hospital",
    facilityAddress: "Example Road, Lahore",
    officialPhone: "042 00000000",
    city: "Lahore",
    province: "Punjab",
    governmentEmploymentVerified: true,
    governmentVerifiedAt: checkedAt,
    pmdcVerifiedAt: checkedAt,
    facilityVerifiedAt: checkedAt,
  },
];

export class FixtureSourceAdapter implements SourceAdapter {
  readonly name = "four-city-fixture";

  async fetch() {
    return fixtures;
  }
}
